### ISSUE TITLE
(Sprint 4) Construção do Frontend da Aplicação

### ISSUE THREAD

**Issue by victorthayashi** [2023M7T3-Inteli/Projeto2#84]
Deploy da solução - não realizado, há “Preencher seguindo as orientações da Adalove” no markdown.

Correção realizada dia 26/09.

**Comment by sofipimazzoni** [comment]
prof, acho que você colou repetido sem querer, mas você criou uma issue de deploy que aborda o mesmo problema e estamos conversando sobre ele por lá.
