### ISSUE TITLE
(Sprint 4) Implementação do frontend com o framework ou biblioteca desejada

### ISSUE THREAD

**Issue by victorthayashi** [2023M7T3-Inteli/Projeto2#85]
Requisitos funcionais e não funcionais do projeto - as descrições de requisitos estão genéricas e alguns requisitos funcionais estão com aspectos não funcionais embutidos. Por exemplo: “O usuário deve ter acesso a antigas pesquisas” -> pesquisas de alguns dias atrás ou meses atrás?; “O sistema deve compreender corretamente a pergunta do usuário e trazer uma resposta com algum fundamento” -> qual o nível de precisão aceito?; “A aplicação deve ser projetada para funcionar em smartphones, permitindo que o time de vendas da IBM acesse facilmente as informações enquanto estiver em deslocamento” -> em quais smartphones? Modelos com sistemas operacionais muito antigos podem apresentar problemas de compatibilidade; “O sistema deve ser fluido e rápido” -> o que caracteriza um sistema ser fluido? Quão rápido?; “O sistema deve ser escalável” -> sob que limites de carga?. O RNF06 “O sistema deve rodar na nuvem” é uma restrição, e não um requisito não funcional. O RNF10 “O sistema deve ser implementado na IBM” também é uma restrição e não um requisito não funcional.

Ambiente de desenvolvimento - não foram encontrados instruções de configuração do ambiente de desenvolvimento em português produzidos pelo grupo.

Correção realizada dia 26/09.

**Comment by sofipimazzoni** [comment]
Prof, essa parte do artefato pediu coisas que o grupo já havia feito na sprint 1 ou 2 se eu não me engano. Considerando isso, eu apenas referenciei elas nessa sessão, para não ter que fazer tudo de novo. Isso em um geral acho que você conseguiu entender bem, mas mesmo assim falou para a gente que sentiu falta da implementação do frontend e suas bibliotecas, então segue abaixo o link da sessão do documento no qual você pode encontrar essas informações:

https://github.com/2023M7T3-Inteli/Projeto2/blob/main/docs/index.md#pilha-de-tecnologias-para-implementar-a-proposta-de-ux
