### ISSUE TITLE
(Sprint 4) Deploy da solução

### ISSUE THREAD

**Issue by victorthayashi** [2023M7T3-Inteli/Projeto2#87]
Deploy da solução - não realizado, há “Preencher seguindo as orientações da Adalove” no markdown.

Correção realizada dia 26/09.

**Comment by sofipimazzoni** [comment]
prof, como existem 2 sessões de deploy da solução na documentação, e a segunda é praticamente igual a primeira, só tem algumas coisas de diferente, o Pedro adicionou o que faltava na primeira sessão de deploy. Por conta disso, na segunda sessão nós apenas referenciamos a primeira. Segue o link da primeira abaixo:

https://github.com/2023M7T3-Inteli/Projeto2/blob/main/docs/index.md#processo-de-deploy-do-algoritmo-em-nuvem-comercial

**Comment by victorthayashi** [comment]
ok. Na seção "Deploy" (https://github.com/2023M7T3-Inteli/Projeto2/blob/main/docs/index.md#deploy-da-solu%C3%A7%C3%A3o), favor referenciar corretamente, de forma a substituir o "Preencher seguindo as orientações da Adalove."

**Comment by sofipimazzoni** [comment]
feito prof! :) você pode conferir aqui https://github.com/2023M7T3-Inteli/Projeto2/blob/main/docs/index.md#deploy-da-solu%C3%A7%C3%A3o
